# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HamtF_GWl7UEiU27p0b7CbmehsIO0N7f
"""

#!pip install streamlit

import streamlit as st
import pickle
import numpy as np

# Load model and vectorizer
model = pickle.load(open('sentiment_model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

# Title
st.title("Sentiment Analysis App")
st.write("Enter a sentence, and the model will predict its sentiment.")

# Text input
user_input = st.text_area("Enter a sentence or review:", height=150)

if st.button("Analyze Sentiment"):
    if user_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        # Preprocess and vectorize input
        input_vector = vectorizer.transform([user_input])
        prediction = model.predict(input_vector)[0]
        proba = max(model.predict_proba(input_vector)[0]) * 100

        # Show result
        if prediction == 2:
            st.success(f"😊 Positive Sentiment ({proba:.2f}% confidence)")
        elif prediction ==1:
            st.success(f"☹️ Neutral Sentiment ({proba:.2f}% confidence)")
        else:
            st.error(f"☹️ Negative Sentiment ({proba:.2f}% confidence)")

