# -*- coding: utf-8 -*-
"""launch_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djLR9_a44HnqmRDHgYpJRRi1M4D4p1Jv
"""

import subprocess
import time
from pyngrok import ngrok

# Step 1: Launch Streamlit app
streamlit_process = subprocess.Popen(["streamlit", "run", "app.py"])

# Wait for a few seconds to ensure Streamlit has started
time.sleep(5)

# Step 2: Create a public URL with ngrok
public_url = ngrok.connect(8501)
print(f"\n🌐 Your app is live at: {public_url}\n")

try:
    # Keep script running to maintain ngrok tunnel
    streamlit_process.wait()
except KeyboardInterrupt:
    print("\n❌ Shutting down...")
    streamlit_process.terminate()
    ngrok.disconnect(public_url)

