# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wuC-lYEA3Ps5mT-6qWcFUJeRRZDaxHzD
"""

streamlit
scikit-learn    #sklearn
pandas
numpy
pickle5